name: Test application on Pull Request
run-name: Test application on Pull Request
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
env:
  METIS_SERVICE_NAME: sequelize_github
  METIS_SERVICE_VERSION: 1
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/demo?schema=imdb
  METIS_API_KEY: pa7gxFw44xa6alSfZVX0v5DRBk3Yfzao5KzOVyOp
  TOKEN_FOR_GITHUB_ACTION: ${{ secrets.PR_TOKEN_GITHUB }}

jobs:
  Run-Tests-With-Metis-On-Pull-Request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    services:
      postgres:
        image: public.ecr.aws/o2c0x5x8/metis-demo-mini-db:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#      metis-otel:
#        image: public.ecr.aws/o2c0x5x8/metis-otel-collector:latest
#        env:
#          CONNECTION_STRING: postgresql://postgres:postgres@postgres:5432/demo?schema=imdb
#          METIS_API_KEY: r1cfLS7ao04PtzJpd2ZuJ3EFFvTmCwTn86f6Hwwv
#          APP_TAG_PR: ${{ github.event.pull_request.title }}
#        ports:
#          - 4317:4317
#          - 4318:4318

    steps:
#      - name: Configure metis PR
#        id: tag_pr
#        uses: metis-data/test-queries-analyzer@v1
#        with:
#          metis_api_key: ${{ vars.METIS_API_KEY }}
#          github_token: ${{ secrets.PR_TOKEN_GITHUB }}
      - name: Setup metis collector
        uses: metis-data/test-collector@v1
        with:
          connection-string: postgresql://postgres:postgres@postgres:5432/demo?schema=imdb
          metis-api-key: pa7gxFw44xa6alSfZVX0v5DRBk3Yfzao5KzOVyOp
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-url: 'https://dev.metisdata.io'
          exporter-target-url: 'https://ingest-stg.metisdata.io'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run tests
#        env:
#          METIS_TAG_PR: ${{ steps.tag_pr.outputs.pr_tag  }}
        run: npm run test